### PR TITLE
Fix Makefile example targets

### PR DESCRIPTION
**Pull request by Theodus**

### CODE REVIEW

**Review by SeanTAllen — APPROVED** [review]
Seems good to me and if it works correctly (haven't tested), I would support making this change across all the repos.

**Comment by Theodus** [comment]
Ok, I'll make this change across the repos

**Comment by btab** [comment]
Hey @Theodus, this change has the same problem as $(test_binaries) had. Namely that the build targets end up with a ".exe" suffix on Windows.

I was going to try adding a similar clause to deal with this, namely...
```
ifneq ( ,$(WINDIR))
	EXAMPLES_BINARIES := $(addsuffix .exe,${EXAMPLES_BINARIES})
endif
```

...but the `$*` expansion used in the make rule you added then turns the source file specification into garbage 😋

Essentially, we can't bind the source files in the compile clause to the target. Not sure on the best way to fix this and wondered whether you had any ideas?

I can then apply the pattern to the other ponylang repos.

**Comment by btab** [comment]
OK I think I have a solution in #28

**Pull request merged**
